<a href="https://colab.research.google.com/github/RAMkong/Pytorchpractice/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
torch.__version__

'2.1.0+cu121'

In [8]:
mata=torch.rand(1,2,3)
mata

tensor([[[0.5836, 0.1632, 0.0147],
         [0.7918, 0.0412, 0.5841]]])

In [13]:
matb=mata.squeeze()
matb

tensor([[0.5836, 0.1632, 0.0147],
        [0.7918, 0.0412, 0.5841]])

In [17]:
matb.size()


torch.Size([2, 3])

In [18]:
mata.size()

torch.Size([1, 2, 3])

In [20]:
matc=matb.unsqueeze(dim=0)
matc

tensor([[[0.5836, 0.1632, 0.0147],
         [0.7918, 0.0412, 0.5841]]])

In [22]:
matc.size()

torch.Size([1, 2, 3])