<a href="https://colab.research.google.com/github/RAMkong/Pytorchpractice/blob/main/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch

**exercises for fundamentals in pytorch**

In [4]:
rand_tensor=torch.rand(7,7)
rand_tensor

tensor([[0.8174, 0.5013, 0.6218, 0.4944, 0.9542, 0.0108, 0.6751],
        [0.9804, 0.8902, 0.8058, 0.0338, 0.3651, 0.3194, 0.4122],
        [0.2822, 0.2687, 0.9551, 0.7794, 0.8913, 0.4107, 0.5536],
        [0.8553, 0.7521, 0.2752, 0.8625, 0.6618, 0.2279, 0.8007],
        [0.7747, 0.1469, 0.9810, 0.1455, 0.0044, 0.8293, 0.0370],
        [0.0462, 0.1170, 0.0316, 0.8077, 0.2454, 0.0831, 0.6083],
        [0.6390, 0.9030, 0.1440, 0.9170, 0.5327, 0.3989, 0.4826]])

In [8]:
#multiplying the above matrix by a [1,7] matrix

mul_tensor=torch.rand(1,7)
result_matrix= torch.matmul(rand_tensor,mul_tensor.T)
#"T" stands for transpose
result_matrix


tensor([[1.6232],
        [1.4268],
        [2.2538],
        [1.7426],
        [1.6122],
        [0.8901],
        [1.7708]])

In [9]:
#setting a manual seed
torch.manual_seed(0)
rand=torch.rand(7,7)
mul=torch.rand(1,7)
result=torch.matmul(rand,mul.T)
result

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])